language: cpp
before_install:
 - sudo apt-get update
 - sudo apt-get install libgtest-dev
 - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
before_script:
 - ./autogen.sh
script: "cd test/gtest && sh ./.travis_build.sh"
branches:
  only:
    - master
    - sidx_test
